validate source file

diff --git a/script b/script
--- a/script
+++ b/script
@@ -1,7 +1,7 @@
 #! /usr/bash
 
 usage () {
-    echo "Usage: $0 <source file> <target aws bucket> [-new filename] [-prefix]"
+    echo "Usage: '$0' <source file> <target aws bucket> [-new filename] [-prefix]"
     exit 1
 }
 
@@ -14,6 +14,46 @@ fi
 
 source_file=$1
 target_bucket=$2
+
+#validate source file
+if [[ -e "$source_file" ]];
+then
+    if [[ -r "$source_file" ]];
+    then
+        if [[ -f "$source_file" ]];
+        then
+            :
+        elif [[ -d "$source_file" ]];
+        then
+            while true; 
+            do
+                read -r -p "You're attempting to upload a directory and all of its content, continue? Y-[Yes], N-[No, cancel]" recursive
+                case "$recursive" in
+                    [Yy])
+                        recursive=true
+                        break
+                        ;;
+                    [Nn])
+                        echo "Operation cancelled."
+                        exit 1
+                        ;;
+                    *)
+                        echo "Invalid response, please try again"
+                        ;;
+                esac
+            done
+        else
+            echo "Invalid source file type. Please try again."
+            exit 1
+        fi
+    else
+        echo "Sorry, you don't have read permissions for the source file"
+        exit 1
+    fi
+else
+    echo "There's no such file or directory. Please try again."
+    exit 1
+fi
 
 #Accept and validate against empty input
 read_input(){
